export const hotels = [
    {
        rasim: {
            korinish: "https://frankfurt.apollo.olxcdn.com/v1/files/lrkqfpyrn52e-UZ/image;s=1500x1000",
            spalni: "https://fullhouse.uz/d/temno-fioletovyy_interyer_spalni.jpg",
            mehmonxona: "https://lh6.googleusercontent.com/mMcnT3yd5I3fjV5OFCG7gi7eL8lqo7ta39S1LcTvmqnScNQZjIfUCNGnnfDPzXbW_lzz37pAKq0QVNHr66S88uK3GEvkgVK1e1ylT0M-SfJke4M0xqEHGjLbMC-zqcFm1MLPdWY",
            hamom: "https://www.mcdonaldjoneshomes.com.au/sites/default/files/inline-images/san-marino-encore-single-storey-home-design-ensuite.jpg",
            oshxona: "https://cf.ltkcdn.net/interiordesign/images/orig/273067-1600x1066-basics-contemporary-kitchen-design.jpg",
            bolalarXonasi: "https://fazo.tv/phaser/wp-content/uploads/2020/05/12054.jpg",
            garaj: "https://cdn.nar.realtor/sites/default/files/assets/images/2208_HD_GarageTrends.png"
        },
        viloyat: "Farg'ona",
        tuman: "Yozyovon",
        hudud: "Shahar",
        location: "Yerda",
        umumiyQavat: "3",
        kvQavati: "3",
        gaz: "Bor",
        svet: "Bor",
        suv: {
            issiq: "Bor",
            sovuq: "Bor",
        },
        konditsioner: "Bor",
        holadelnik: "Bor",
        holati: "Zo'r",
        ijaraNarxi: "200 ming"
    },
    {
        rasim: {
            korinish: "https://frankfurt.apollo.olxcdn.com/v1/files/lrkqfpyrn52e-UZ/image;s=1500x1000",
            spalni: "https://fullhouse.uz/d/temno-fioletovyy_interyer_spalni.jpg",
            mehmonxona: "https://lh6.googleusercontent.com/mMcnT3yd5I3fjV5OFCG7gi7eL8lqo7ta39S1LcTvmqnScNQZjIfUCNGnnfDPzXbW_lzz37pAKq0QVNHr66S88uK3GEvkgVK1e1ylT0M-SfJke4M0xqEHGjLbMC-zqcFm1MLPdWY",
            hamom: "https://www.mcdonaldjoneshomes.com.au/sites/default/files/inline-images/san-marino-encore-single-storey-home-design-ensuite.jpg",
            oshxona: "https://cf.ltkcdn.net/interiordesign/images/orig/273067-1600x1066-basics-contemporary-kitchen-design.jpg",
            bolalarXonasi: "https://fazo.tv/phaser/wp-content/uploads/2020/05/12054.jpg",
            garaj: "https://cdn.nar.realtor/sites/default/files/assets/images/2208_HD_GarageTrends.png"
        },
        viloyat: "Toshkent",
        tuman: "Toshkent",
        hudud: "Sergili",
        location: "Yerda",
        umumiyQavat: "2",
        kvQavati: "5",
        gaz: "Bor",
        svet: "Bor",
        suv: {
            issiq: "Bor",
            sovuq: "Bor",
        },
        konditsioner: "Yoq",
        holadelnik: "Bor",
        holati: "Alo",
        ijaraNarxi: "300 ming"
    },
    {
        rasim: {
            korinish: "https://frankfurt.apollo.olxcdn.com/v1/files/lrkqfpyrn52e-UZ/image;s=1500x1000",
            spalni: "https://fullhouse.uz/d/temno-fioletovyy_interyer_spalni.jpg",
            mehmonxona: "https://lh6.googleusercontent.com/mMcnT3yd5I3fjV5OFCG7gi7eL8lqo7ta39S1LcTvmqnScNQZjIfUCNGnnfDPzXbW_lzz37pAKq0QVNHr66S88uK3GEvkgVK1e1ylT0M-SfJke4M0xqEHGjLbMC-zqcFm1MLPdWY",
            hamom: "https://www.mcdonaldjoneshomes.com.au/sites/default/files/inline-images/san-marino-encore-single-storey-home-design-ensuite.jpg",
            oshxona: "https://cf.ltkcdn.net/interiordesign/images/orig/273067-1600x1066-basics-contemporary-kitchen-design.jpg",
            bolalarXonasi: "https://fazo.tv/phaser/wp-content/uploads/2020/05/12054.jpg",
            garaj: "https://cdn.nar.realtor/sites/default/files/assets/images/2208_HD_GarageTrends.png"
        },
        viloyat: "Andijon",
        tuman: "Asaka",
        hudud: "Qishloq",
        location: "Yerda",
        umumiyQavat: "1",
        kvQavati: "1",
        gaz: "Yoq",
        svet: "Bor",
        suv: {
            issiq: "Yoq",
            sovuq: "Bor",
        },
        konditsioner: "YOq",
        holadelnik: "Bor",
        holati: "O'rtacha",
        ijaraNarxi: "50 ming"
    },
    {
        rasim: {
            korinish: "https://frankfurt.apollo.olxcdn.com/v1/files/lrkqfpyrn52e-UZ/image;s=1500x1000",
            spalni: "https://fullhouse.uz/d/temno-fioletovyy_interyer_spalni.jpg",
            mehmonxona: "https://lh6.googleusercontent.com/mMcnT3yd5I3fjV5OFCG7gi7eL8lqo7ta39S1LcTvmqnScNQZjIfUCNGnnfDPzXbW_lzz37pAKq0QVNHr66S88uK3GEvkgVK1e1ylT0M-SfJke4M0xqEHGjLbMC-zqcFm1MLPdWY",
            hamom: "https://www.mcdonaldjoneshomes.com.au/sites/default/files/inline-images/san-marino-encore-single-storey-home-design-ensuite.jpg",
            oshxona: "https://cf.ltkcdn.net/interiordesign/images/orig/273067-1600x1066-basics-contemporary-kitchen-design.jpg",
            bolalarXonasi: "https://fazo.tv/phaser/wp-content/uploads/2020/05/12054.jpg",
            garaj: "https://cdn.nar.realtor/sites/default/files/assets/images/2208_HD_GarageTrends.png"
        },
        viloyat: "Namangan",
        tuman: "Chust",
        hudud: "Shahar",
        location: "Yerda",
        umumiyQavat: "5",
        kvQavati: "5",
        gaz: "Bor",
        svet: "Bor",
        suv: {
            issiq: "Bor",
            sovuq: "Bor",
        },
        konditsioner: "Bor",
        holadelnik: "Bor",
        holati: "Alo",
        ijaraNarxi: "500 ming"
    },
    {
        rasim: {
            korinish: "https://frankfurt.apollo.olxcdn.com/v1/files/lrkqfpyrn52e-UZ/image;s=1500x1000",
            spalni: "https://fullhouse.uz/d/temno-fioletovyy_interyer_spalni.jpg",
            mehmonxona: "https://lh6.googleusercontent.com/mMcnT3yd5I3fjV5OFCG7gi7eL8lqo7ta39S1LcTvmqnScNQZjIfUCNGnnfDPzXbW_lzz37pAKq0QVNHr66S88uK3GEvkgVK1e1ylT0M-SfJke4M0xqEHGjLbMC-zqcFm1MLPdWY",
            hamom: "https://www.mcdonaldjoneshomes.com.au/sites/default/files/inline-images/san-marino-encore-single-storey-home-design-ensuite.jpg",
            oshxona: "https://cf.ltkcdn.net/interiordesign/images/orig/273067-1600x1066-basics-contemporary-kitchen-design.jpg",
            bolalarXonasi: "https://fazo.tv/phaser/wp-content/uploads/2020/05/12054.jpg",
            garaj: "https://cdn.nar.realtor/sites/default/files/assets/images/2208_HD_GarageTrends.png"
        },
        viloyat: "Surxandaryo",
        tuman: "Surxandaryo",
        hudud: "Shahar",
        location: "Yerda",
        umumiyQavat: "2",
        kvQavati: "3",
        gaz: "Bor",
        svet: "Yoq",
        suv: {
            issiq: "Yo",
            sovuq: "Bor",
        },
        konditsioner: "Bor",
        holadelnik: "Yo",
        holati: "Ortacha",
        ijaraNarxi: "150 ming"
    },
    {
        rasim: {
            korinish: "https://frankfurt.apollo.olxcdn.com/v1/files/lrkqfpyrn52e-UZ/image;s=1500x1000",
            spalni: "https://fullhouse.uz/d/temno-fioletovyy_interyer_spalni.jpg",
            mehmonxona: "https://lh6.googleusercontent.com/mMcnT3yd5I3fjV5OFCG7gi7eL8lqo7ta39S1LcTvmqnScNQZjIfUCNGnnfDPzXbW_lzz37pAKq0QVNHr66S88uK3GEvkgVK1e1ylT0M-SfJke4M0xqEHGjLbMC-zqcFm1MLPdWY",
            hamom: "https://www.mcdonaldjoneshomes.com.au/sites/default/files/inline-images/san-marino-encore-single-storey-home-design-ensuite.jpg",
            oshxona: "https://cf.ltkcdn.net/interiordesign/images/orig/273067-1600x1066-basics-contemporary-kitchen-design.jpg",
            bolalarXonasi: "https://fazo.tv/phaser/wp-content/uploads/2020/05/12054.jpg",
            garaj: "https://cdn.nar.realtor/sites/default/files/assets/images/2208_HD_GarageTrends.png"
        },
        viloyat: "Qashqadaryo",
        tuman: "Termiz",
        hudud: "Tuman",
        location: "Yerda",
        umumiyQavat: "7",
        kvQavati: "7",
        gaz: "Bor",
        svet: "Bor",
        suv: {
            issiq: "Yoq",
            sovuq: "Bor",
        },
        konditsioner: "Yoq",
        holadelnik: "Yoq",
        holati: "Alo",
        ijaraNarxi: "50 ming"
    },
    {
        rasim: {
            korinish: "https://frankfurt.apollo.olxcdn.com/v1/files/lrkqfpyrn52e-UZ/image;s=1500x1000",
            spalni: "https://fullhouse.uz/d/temno-fioletovyy_interyer_spalni.jpg",
            mehmonxona: "https://lh6.googleusercontent.com/mMcnT3yd5I3fjV5OFCG7gi7eL8lqo7ta39S1LcTvmqnScNQZjIfUCNGnnfDPzXbW_lzz37pAKq0QVNHr66S88uK3GEvkgVK1e1ylT0M-SfJke4M0xqEHGjLbMC-zqcFm1MLPdWY",
            hamom: "https://www.mcdonaldjoneshomes.com.au/sites/default/files/inline-images/san-marino-encore-single-storey-home-design-ensuite.jpg",
            oshxona: "https://cf.ltkcdn.net/interiordesign/images/orig/273067-1600x1066-basics-contemporary-kitchen-design.jpg",
            bolalarXonasi: "https://fazo.tv/phaser/wp-content/uploads/2020/05/12054.jpg",
            garaj: "https://cdn.nar.realtor/sites/default/files/assets/images/2208_HD_GarageTrends.png"
        },
        viloyat: "Jizzax",
        tuman: "Zomin",
        hudud: "Toglar",
        location: "Yerda",
        umumiyQavat: "1",
        kvQavati: "1",
        gaz: "Yoq",
        svet: "Bor",
        suv: {
            issiq: "Yoq",
            sovuq: "Bor",
        },
        konditsioner: "Yoq",
        holadelnik: "Bor",
        holati: "O'rtacha",
        ijaraNarxi: "150 ming"
    },
    {
        rasim: {
            korinish: "https://frankfurt.apollo.olxcdn.com/v1/files/lrkqfpyrn52e-UZ/image;s=1500x1000",
            spalni: "https://fullhouse.uz/d/temno-fioletovyy_interyer_spalni.jpg",
            mehmonxona: "https://lh6.googleusercontent.com/mMcnT3yd5I3fjV5OFCG7gi7eL8lqo7ta39S1LcTvmqnScNQZjIfUCNGnnfDPzXbW_lzz37pAKq0QVNHr66S88uK3GEvkgVK1e1ylT0M-SfJke4M0xqEHGjLbMC-zqcFm1MLPdWY",
            hamom: "https://www.mcdonaldjoneshomes.com.au/sites/default/files/inline-images/san-marino-encore-single-storey-home-design-ensuite.jpg",
            oshxona: "https://cf.ltkcdn.net/interiordesign/images/orig/273067-1600x1066-basics-contemporary-kitchen-design.jpg",
            bolalarXonasi: "https://fazo.tv/phaser/wp-content/uploads/2020/05/12054.jpg",
            garaj: "https://cdn.nar.realtor/sites/default/files/assets/images/2208_HD_GarageTrends.png"
        },
        viloyat: "Navoiy",
        tuman: "Qizilqum",
        hudud: "Chol",
        location: "Yerda",
        umumiyQavat: "5",
        kvQavati: "5",
        gaz: "Bor",
        svet: "Bor",
        suv: {
            issiq: "Bor",
            sovuq: "Bor",
        },
        konditsioner: "Bor",
        holadelnik: "Bor",
        holati: "Alo",
        ijaraNarxi: "100 ming"
    },
    {
        rasim: {
            korinish: "https://frankfurt.apollo.olxcdn.com/v1/files/lrkqfpyrn52e-UZ/image;s=1500x1000",
            spalni: "https://fullhouse.uz/d/temno-fioletovyy_interyer_spalni.jpg",
            mehmonxona: "https://lh6.googleusercontent.com/mMcnT3yd5I3fjV5OFCG7gi7eL8lqo7ta39S1LcTvmqnScNQZjIfUCNGnnfDPzXbW_lzz37pAKq0QVNHr66S88uK3GEvkgVK1e1ylT0M-SfJke4M0xqEHGjLbMC-zqcFm1MLPdWY",
            hamom: "https://www.mcdonaldjoneshomes.com.au/sites/default/files/inline-images/san-marino-encore-single-storey-home-design-ensuite.jpg",
            oshxona: "https://cf.ltkcdn.net/interiordesign/images/orig/273067-1600x1066-basics-contemporary-kitchen-design.jpg",
            bolalarXonasi: "https://fazo.tv/phaser/wp-content/uploads/2020/05/12054.jpg",
            garaj: "https://cdn.nar.realtor/sites/default/files/assets/images/2208_HD_GarageTrends.png"
        },
        viloyat: "Xorazm",
        tuman: "Urganch",
        hudud: "Shahar",
        location: "Yerda",
        umumiyQavat: "2",
        kvQavati: "3",
        gaz: "Bor",
        svet: "Bor",
        suv: {
            issiq: "Bor",
            sovuq: "Bor",
        },
        konditsioner: "Bor",
        holadelnik: "Bor",
        holati: "Zo'r",
        ijaraNarxi: "300 ming"
    },
    {
        rasim: {
            korinish: "https://frankfurt.apollo.olxcdn.com/v1/files/lrkqfpyrn52e-UZ/image;s=1500x1000",
            spalni: "https://fullhouse.uz/d/temno-fioletovyy_interyer_spalni.jpg",
            mehmonxona: "https://lh6.googleusercontent.com/mMcnT3yd5I3fjV5OFCG7gi7eL8lqo7ta39S1LcTvmqnScNQZjIfUCNGnnfDPzXbW_lzz37pAKq0QVNHr66S88uK3GEvkgVK1e1ylT0M-SfJke4M0xqEHGjLbMC-zqcFm1MLPdWY",
            hamom: "https://www.mcdonaldjoneshomes.com.au/sites/default/files/inline-images/san-marino-encore-single-storey-home-design-ensuite.jpg",
            oshxona: "https://cf.ltkcdn.net/interiordesign/images/orig/273067-1600x1066-basics-contemporary-kitchen-design.jpg",
            bolalarXonasi: "https://fazo.tv/phaser/wp-content/uploads/2020/05/12054.jpg",
            garaj: "https://cdn.nar.realtor/sites/default/files/assets/images/2208_HD_GarageTrends.png"
        },
        viloyat: "Toshkent",
        tuman: "Toshkent",
        hudud: "Sergili",
        location: "Yerda",
        umumiyQavat: "2",
        kvQavati: "5",
        gaz: "Bor",
        svet: "Bor",
        suv: {
            issiq: "Bor",
            sovuq: "Bor",
        },
        konditsioner: "Yoq",
        holadelnik: "Bor",
        holati: "Alo",
        ijaraNarxi: "300 ming"
    },
    {
        rasim: {
            korinish: "https://frankfurt.apollo.olxcdn.com/v1/files/lrkqfpyrn52e-UZ/image;s=1500x1000",
            spalni: "https://fullhouse.uz/d/temno-fioletovyy_interyer_spalni.jpg",
            mehmonxona: "https://lh6.googleusercontent.com/mMcnT3yd5I3fjV5OFCG7gi7eL8lqo7ta39S1LcTvmqnScNQZjIfUCNGnnfDPzXbW_lzz37pAKq0QVNHr66S88uK3GEvkgVK1e1ylT0M-SfJke4M0xqEHGjLbMC-zqcFm1MLPdWY",
            hamom: "https://www.mcdonaldjoneshomes.com.au/sites/default/files/inline-images/san-marino-encore-single-storey-home-design-ensuite.jpg",
            oshxona: "https://cf.ltkcdn.net/interiordesign/images/orig/273067-1600x1066-basics-contemporary-kitchen-design.jpg",
            bolalarXonasi: "https://fazo.tv/phaser/wp-content/uploads/2020/05/12054.jpg",
            garaj: "https://cdn.nar.realtor/sites/default/files/assets/images/2208_HD_GarageTrends.png"
        },
        viloyat: "Andijon",
        tuman: "Asaka",
        hudud: "Qishloq",
        location: "Yerda",
        umumiyQavat: "1",
        kvQavati: "1",
        gaz: "Yoq",
        svet: "Bor",
        suv: {
            issiq: "Yoq",
            sovuq: "Bor",
        },
        konditsioner: "YOq",
        holadelnik: "Bor",
        holati: "O'rtacha",
        ijaraNarxi: "50 ming"
    },
    {
        rasim: {
            korinish: "https://frankfurt.apollo.olxcdn.com/v1/files/lrkqfpyrn52e-UZ/image;s=1500x1000",
            spalni: "https://fullhouse.uz/d/temno-fioletovyy_interyer_spalni.jpg",
            mehmonxona: "https://lh6.googleusercontent.com/mMcnT3yd5I3fjV5OFCG7gi7eL8lqo7ta39S1LcTvmqnScNQZjIfUCNGnnfDPzXbW_lzz37pAKq0QVNHr66S88uK3GEvkgVK1e1ylT0M-SfJke4M0xqEHGjLbMC-zqcFm1MLPdWY",
            hamom: "https://www.mcdonaldjoneshomes.com.au/sites/default/files/inline-images/san-marino-encore-single-storey-home-design-ensuite.jpg",
            oshxona: "https://cf.ltkcdn.net/interiordesign/images/orig/273067-1600x1066-basics-contemporary-kitchen-design.jpg",
            bolalarXonasi: "https://fazo.tv/phaser/wp-content/uploads/2020/05/12054.jpg",
            garaj: "https://cdn.nar.realtor/sites/default/files/assets/images/2208_HD_GarageTrends.png"
        },
        viloyat: "Namangan",
        tuman: "Chust",
        hudud: "Shahar",
        location: "Yerda",
        umumiyQavat: "5",
        kvQavati: "5",
        gaz: "Bor",
        svet: "Bor",
        suv: {
            issiq: "Bor",
            sovuq: "Bor",
        },
        konditsioner: "Bor",
        holadelnik: "Bor",
        holati: "Alo",
        ijaraNarxi: "500 ming"
    },
]
